/*
 * SQLite schema. Mirrors the Zod schemas in @health-mcp/shared; enum values
 * are imported from there so the two cannot drift apart.
 *
 * Conventions:
 * - IDs are UUID text, generated by the app.
 * - Dates are ISO-8601 text: `YYYY-MM-DD` for dates, UTC `...Z` for
 *   timestamps. Callers must normalize offsets to UTC before writing so that
 *   text ordering matches time ordering.
 * - Every health record belongs to a patient and is deleted with it.
 *
 * This file must not use relative imports: drizzle-kit loads it directly.
 */
import { randomUUID } from "node:crypto";

import {
  ChatRoleSchema,
  LabFlagSchema,
  MedicationStatusSchema,
  MilestoneStatusSchema,
  PatientStatusSchema,
  SexSchema,
  type ToolCall,
  VitalTypeSchema,
} from "@health-mcp/shared";
import { type SQL, sql } from "drizzle-orm";
import { type AnySQLiteColumn, check, index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => randomUUID());

const patientId = () =>
  text("patient_id")
    .notNull()
    .references(() => patients.id, { onDelete: "cascade" });

/** Values of a Zod enum as the non-empty tuple Drizzle expects. */
const values = <T extends string>(schema: { options: T[] }) => schema.options as [T, ...T[]];

const nowUtc = sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`;

/** `CHECK (column IN (...))` for a text enum column. */
const oneOf = (column: AnySQLiteColumn, values: readonly string[]): SQL =>
  sql`${column} in (${sql.join(
    values.map((value) => sql.raw(`'${value}'`)),
    sql`, `,
  )})`;

// ------------------------------------------------------------------- patients

export const patients = sqliteTable(
  "patients",
  {
    id: id(),
    mrn: text("mrn").notNull().unique(),
    firstName: text("first_name").notNull(),
    lastName: text("last_name").notNull(),
    dateOfBirth: text("date_of_birth").notNull(),
    sex: text("sex", { enum: values(SexSchema) }).notNull(),
    status: text("status", { enum: values(PatientStatusSchema) }).notNull().default("active"),
    diagnosis: text("diagnosis").notNull(),
    surgeryDate: text("surgery_date"),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(nowUtc),
    updatedAt: text("updated_at")
      .notNull()
      .default(nowUtc)
      .$onUpdateFn(() => new Date().toISOString()),
  },
  (t) => [
    check("patients_sex_check", oneOf(t.sex, SexSchema.options)),
    check("patients_status_check", oneOf(t.status, PatientStatusSchema.options)),
    index("patients_status_idx").on(t.status),
  ],
);

// ------------------------------------------------------------- health records

export const labResults = sqliteTable(
  "lab_results",
  {
    id: id(),
    patientId: patientId(),
    testName: text("test_name").notNull(),
    value: real("value").notNull(),
    unit: text("unit").notNull(),
    referenceLow: real("reference_low"),
    referenceHigh: real("reference_high"),
    flag: text("flag", { enum: values(LabFlagSchema) }),
    collectedAt: text("collected_at").notNull(),
  },
  (t) => [
    check("lab_results_flag_check", oneOf(t.flag, LabFlagSchema.options)),
    index("lab_results_patient_collected_idx").on(t.patientId, t.collectedAt),
    index("lab_results_patient_test_idx").on(t.patientId, t.testName),
  ],
);

export const vitalSigns = sqliteTable(
  "vital_signs",
  {
    id: id(),
    patientId: patientId(),
    type: text("type", { enum: values(VitalTypeSchema) }).notNull(),
    value: real("value").notNull(),
    unit: text("unit").notNull(),
    recordedAt: text("recorded_at").notNull(),
  },
  (t) => [
    check("vital_signs_type_check", oneOf(t.type, VitalTypeSchema.options)),
    index("vital_signs_patient_type_recorded_idx").on(t.patientId, t.type, t.recordedAt),
  ],
);

export const medications = sqliteTable(
  "medications",
  {
    id: id(),
    patientId: patientId(),
    name: text("name").notNull(),
    dosage: text("dosage").notNull(),
    frequency: text("frequency").notNull(),
    route: text("route"),
    status: text("status", { enum: values(MedicationStatusSchema) }).notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date"),
  },
  (t) => [
    check("medications_status_check", oneOf(t.status, MedicationStatusSchema.options)),
    index("medications_patient_status_idx").on(t.patientId, t.status),
  ],
);

export const symptoms = sqliteTable(
  "symptoms",
  {
    id: id(),
    patientId: patientId(),
    name: text("name").notNull(),
    severity: integer("severity").notNull(),
    notes: text("notes"),
    recordedAt: text("recorded_at").notNull(),
  },
  (t) => [
    check("symptoms_severity_check", sql`${t.severity} between 0 and 10`),
    index("symptoms_patient_recorded_idx").on(t.patientId, t.recordedAt),
  ],
);

export const recoveryMilestones = sqliteTable(
  "recovery_milestones",
  {
    id: id(),
    patientId: patientId(),
    title: text("title").notNull(),
    description: text("description"),
    status: text("status", { enum: values(MilestoneStatusSchema) }).notNull().default("pending"),
    targetDate: text("target_date"),
    achievedAt: text("achieved_at"),
  },
  (t) => [
    check("recovery_milestones_status_check", oneOf(t.status, MilestoneStatusSchema.options)),
    index("recovery_milestones_patient_status_idx").on(t.patientId, t.status),
  ],
);

// ----------------------------------------------------------------------- chat

export const chatMessages = sqliteTable(
  "chat_messages",
  {
    id: id(),
    patientId: patientId(),
    role: text("role", { enum: values(ChatRoleSchema) }).notNull(),
    content: text("content").notNull(),
    /** JSON array of tool calls made while producing an assistant message. */
    toolCalls: text("tool_calls", { mode: "json" }).$type<ToolCall[]>().notNull().default([]),
    createdAt: text("created_at").notNull().default(nowUtc),
  },
  (t) => [
    check("chat_messages_role_check", oneOf(t.role, ChatRoleSchema.options)),
    index("chat_messages_patient_created_idx").on(t.patientId, t.createdAt),
  ],
);

// ---------------------------------------------------------------- row types

export type PatientRow = typeof patients.$inferSelect;
export type NewPatientRow = typeof patients.$inferInsert;
export type LabResultRow = typeof labResults.$inferSelect;
export type NewLabResultRow = typeof labResults.$inferInsert;
export type VitalSignRow = typeof vitalSigns.$inferSelect;
export type NewVitalSignRow = typeof vitalSigns.$inferInsert;
export type MedicationRow = typeof medications.$inferSelect;
export type NewMedicationRow = typeof medications.$inferInsert;
export type SymptomRow = typeof symptoms.$inferSelect;
export type NewSymptomRow = typeof symptoms.$inferInsert;
export type RecoveryMilestoneRow = typeof recoveryMilestones.$inferSelect;
export type NewRecoveryMilestoneRow = typeof recoveryMilestones.$inferInsert;
export type ChatMessageRow = typeof chatMessages.$inferSelect;
export type NewChatMessageRow = typeof chatMessages.$inferInsert;
